feat: add gum

diff --git a/sw/bin/executable_git_ship b/sw/bin/executable_git_ship
--- a/sw/bin/executable_git_ship
+++ b/sw/bin/executable_git_ship
@@ -7,23 +7,30 @@ function revolver_stop() {
 
 # This script takes one argument and uses it as git commit message
 if [ $# -ne 1 ]; then
-	# read commit message, exit if empty
-	echo "Enter commit message:"
-	read -r commit_message
-	if [ -z "$commit_message" ]; then
-		echo "No commit message given, exiting..."
-		exit 1
-	fi
+	type=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
+	commit_message=$(gum input --value "$type: " --placeholder "Commit message")
 else
 	commit_message=$1
 fi
 
-tput civis
-revolver --style 'dots2' start 'Committing changes...'
-
 # show the list of modified git files that will be committed
 echo " == Modified files == "
 git status --short --untracked-files=no
+
+# empty line
+echo ""
+
+# list only untracked files
+echo " == Untracked files == "
+git ls-files --others --exclude-standard
+
+if ! gum confirm "Commit and push these changes?"; then
+	echo "Aborting"
+	exit 1
+fi
+
+tput civis
+revolver --style 'dots2' start 'Committing changes...'
 
 # Iteration counter
 i=0
